# Generated by Django 5.0.3 on 2024-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slapify_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slapifyuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Artist', 'Artist'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
