# Generated by Django 5.0.3 on 2024-04-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slapify_web_app', '0002_alter_slapifyuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slapifyuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
